### ISSUE TITLE
Cannot save posts, what am I doing wrong?

### ISSUE THREAD

**Issue by saro-saravanan** [blockstack-radiks/lettermesh#3]
The progress bar keeps spinning and the post is never saved. Please let me know if you need any further info to help. Thanks!

![image](https://user-images.githubusercontent.com/43354048/52497959-768c1180-2ba5-11e9-8b48-8e6b727a8415.png)

**Comment by hstove** [comment]
@saro-saravanan it looks like you're having internet connection issues, based on your console. Was that a possibility? My first thought would be to try again and see if those issues persist.

Thanks for trying it out!

**Comment by saro-saravanan** [comment]
Thanks for the answer.  I was not having Internet connection issues.  I had created a document in Graphite and used the URL for that document in the post screen, but I wasn't sure if that document needed to be shared publicly for this to work - that would seem to defeat the purpose. The "Failed to load resource" message indicates that the Graphite URL is the one that's inaccessible.

I would appreciate the help. Radiks seems like a great tool for blockstack developers and I would like to use it. I was just trying to get familiar with it by trying lettermesh.

**Comment by rmcsharry** [comment]
@hstove Lettermesh is cool, but I have the exact same issue. Tried twice to create a post, but it just sticks on saving mode.

The uncaught in promise error, as posted above, occurs when you hit 'create new post'. The page loads and you can fill the form, then hit the create button to actually create the post and a new console error:

```

Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': An object could not be cloned.
    at Object.t.messageJumpContext (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/content-script.js:24:9921)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/content-script.js:24:8583
/_next/static/4jXvnTCqovALRUGqwyzgC/pages/_app.js:1 Object
/_next/static/4jXvnTCqovALRUGqwyzgC/pages/_app.js:1 Object
core.blockstack.org/v1/names/toplobster.id.blockstack&id=1563810690941:1 Failed to load resource: the server responded with a status of 404 ()
/_next/static/chunks/commons.1c11accf3b7b9b1c053c.js:13 Uncaught (in promise) Error: Name not found
    at /_next/static/chunks/commons.1c11accf3b7b9b1c053c.js:13
4chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/content-script.js:24 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': An object could not be cloned.
    at Object.t.messageJumpContext (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/content-script.js:24:9921)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/content-script.js:24:8583
```

I did make my graphite doc public (read only) but that did not help the 3rd time.

I am on latest Chrome on MacOS
